---
- name: Change permission
  file:
    path: ../../development/admin
    mode: '1755'
    
- name: Replacing endpoint value in environment.ts
  lineinfile:
    path: ../../development/admin/client-side/src/environments/environment.ts
    regexp: "apiEndpoint"
    line: "apiEndpoint: 'http://{{ local_ipv4_address }}:3001/api',"

- name: Replacing endpoint value in environment.prod.ts
  lineinfile:
    path: ../../development/admin/client-side/src/environments/environment.prod.ts
    regexp: "apiEndpoint"
    line: "apiEndpoint: 'http://{{ local_ipv4_address }}:3001/api',"

- name: Change to Angular directory
  shell: cd ../../development/admin/client-side

- name: Install Angular packages based on package.json.
  npm:
    path: ../../development/admin/client-side
