---
- name: Installing cQube
  hosts: localhost
  remote_user: root
  vars_files:
    - config.yml

  roles:
   - java
   - python
   - s3_buckets
   - createdb
   - python_flask
   - angular
   - nifi_install
   - nifi_crc
   - nifi_static
   - nifi_attendance
   - nifi_semester
