---
- name: Installing cQube
  hosts: localhost
  remote_user: root
  vars_files:
    - config.yml

  roles:
          - { role: create_base_dir, tags: install }
          - { role: java, tags: install }  
          - { role: python, tags: install }
          - createdb
          - python_flask
          - { role: keycloak, tags: install }
          - { role: grafana, tags: install }
          - angular
          - angular_admin
          - { role: prometheus, tags: install }
          - { role: nifi_params, tags: install }
          - { role: nifi_install, tags: install }
          - { role: nifi_crc, tags: install }
          - { role: nifi_static, tags: install }
          - { role: nifi_attendance, tags: install }
          - { role: nifi_semester, tags: install }
          - { role: nifi_infra, tags: install }
          - { role: nifi_diksha, tags: install }
