---
- hosts: localhost
  connection: local
  tasks:
   - name: Fetch nifi processor group id
     uri:
       url: http://localhost:8080/nifi-api/process-groups/root
       method: GET
     register: processor_id
#   - name: fetch id
#     debug:
#       var: processor_id.json.id

   - name: Get processor group
     uri:
       url: http://localhost:8080/nifi-api/flow/process-groups/{{ processor_id.json.id }}
       method: GET
     register: processor_group
#   - name: fetch processors id
#     debug:
#       var: processor_group.json.processGroupFlow.flow.processGroups[0].component.id #processor_group

   - name: Get processor group #delete this
     uri:
       url: http://localhost:8080/nifi-api/flow/parameter-contexts
       method: GET
     register: pg
#   - name: fetch parameter context id #2nd for testing
#     debug:
#       var: pg.json

   - name: Connection of Parameter context to processor group 
     uri:
       url: http://localhost:8080/nifi-api/process-groups/{{ processor_group.json.processGroupFlow.flow.processGroups[0].component.id }}
       method: PUT
       body_format: json
       body: {"revision": {
            "version": 0,
            "lastModifier": "Ansible"
        },"component":
               {"id": "{{ processor_group.json.processGroupFlow.flow.processGroups[0].component.id }}","parameterContext":{"id": "{{ pg.json.parameterContexts[0].id }}"}}
}


   - name: Get controllers
     uri:
       url: http://localhost:8080/nifi-api/flow/process-groups/{{ processor_group.json.processGroupFlow.flow.processGroups[0].component.id }}/controller-services
       method: GET
     register: controllers_list
#   - name: controllers list print
#     debug:
#       var: controllers_list



   - name: Start controllers
     uri:
       url: http://localhost:8080/nifi-api/controller-services/{{ controllers_list.json.controllerServices[0].id }}
       method: PUT
       body_format: json
       body: {"revision": {
	    "version": "{{ controllers_list.json.controllerServices[0].revision.version }}",
	    "lastModifier": "Ansible"
	},
	"component":
	{"id": "{{ controllers_list.json.controllerServices[0].id }}","state":"ENABLED"}
}

   - name: Start controllers
     uri:
       url: http://localhost:8080/nifi-api/controller-services/{{ controllers_list.json.controllerServices[1].id }}
       method: PUT
       body_format: json
       body: {"revision": {
            "version": "{{ controllers_list.json.controllerServices[1].revision.version }}",
            "lastModifier": "Ansible"
        },
        "component":
        {"id": "{{ controllers_list.json.controllerServices[1].id }}","state":"ENABLED"}
}
    
   - name: Start controllers
     uri:
       url: http://localhost:8080/nifi-api/controller-services/{{ controllers_list.json.controllerServices[2].id }}
       method: PUT
       body_format: json
       body: {"revision": {
            "version": "{{ controllers_list.json.controllerServices[2].revision.version }}",
            "lastModifier": "Ansible"
        },
        "component":
        {"id": "{{ controllers_list.json.controllerServices[2].id }}","state":"ENABLED"}
}

   - name: Start controllers
     uri:
       url: http://localhost:8080/nifi-api/controller-services/{{ controllers_list.json.controllerServices[3].id }}
       method: PUT
       body_format: json
       body: {"revision": {
            "version": "{{ controllers_list.json.controllerServices[3].revision.version }}",
            "lastModifier": "Ansible"
        },
        "component":
        {"id": "{{ controllers_list.json.controllerServices[3].id }}","state":"ENABLED"}
        }

   - name: Start controllers
     uri:
       url: http://localhost:8080/nifi-api/controller-services/{{ controllers_list.json.controllerServices[4].id }}
       method: PUT
       body_format: json
       body: {"revision": {
            "version": "{{ controllers_list.json.controllerServices[4].revision.version }}",
            "lastModifier": "Ansible"
        },
        "component":
        {"id": "{{ controllers_list.json.controllerServices[4].id }}","state":"ENABLED"}
        }



   - name: Start controllers
     uri:
       url: http://localhost:8080/nifi-api/controller-services/{{ controllers_list.json.controllerServices[5].id }}
       method: PUT
       body_format: json
       body: {"revision": {
            "version": "{{ controllers_list.json.controllerServices[5].revision.version }}",
            "lastModifier": "Ansible"
        },
        "component":
        {"id": "{{ controllers_list.json.controllerServices[5].id }}","state":"ENABLED"}
        }
   - name: Start controllers
     uri:
       url: http://localhost:8080/nifi-api/controller-services/{{ controllers_list.json.controllerServices[6].id }}
       method: PUT
       body_format: json
       body: {"revision": {
            "version": "{{ controllers_list.json.controllerServices[6].revision.version }}",
            "lastModifier": "Ansible"
        },
        "component":
        {"id": "{{ controllers_list.json.controllerServices[6].id }}","state":"ENABLED"}
        }
   - name: Start controllers
     uri:
       url: http://localhost:8080/nifi-api/controller-services/{{ controllers_list.json.controllerServices[7].id }}
       method: PUT
       body_format: json
       body: {"revision": {
            "version": "{{ controllers_list.json.controllerServices[7].revision.version }}",
            "lastModifier": "Ansible"
        },
        "component":
        {"id": "{{ controllers_list.json.controllerServices[7].id }}","state":"ENABLED"}
        }

   - name: Start Processor group
     uri:
       url: http://localhost:8080/nifi-api/flow/process-groups/{{ processor_group.json.processGroupFlow.id }}
       method: PUT
       body_format: json
       body: {"id":"{{ processor_group.json.processGroupFlow.id }}","state":"RUNNING"}


        # register: start_controllers_list
        # - name: fetch controllers id
        #  debug:
        # var: start_controllers_list
