---
- name: stop pm2 if running
  become: yes
  shell: pm2 stop client_side

- name: Delete dist folder
  file:
    path: "{{ base_dir }}/cqube/dashboard/client_side/dist"
    state: absent

- name: Delete environment.ts
  file:
    path: "../../development/angular/client-side/src/environments/environment.ts"
    state: absent

- name: Updating environment.ts
  template:
    src: angular_environment.ts.j2
    dest: "../../development/angular/client-side/src/environments/environment.ts"

- name: Delete environment.prod.ts
  file:
    path: "../../development/angular/client-side/src/environments/environment.prod.ts"
    state: absent

- name: Updating environment.prod.ts
  template:
    src: angular_environment.prod.ts.j2
    dest: "../../development/angular/client-side/src/environments/environment.prod.ts"

- name: Building Angular client-side code
  command: ng build --prod
  args:
    chdir: ../../development/angular/client-side

- name: Copying built angular app into client_side directory
  copy:
    src: ../../development/angular/client-side/dist
    dest: "{{ base_dir }}/cqube/dashboard/client_side"

- name: changing ownership
  file:
    path: "{{ base_dir }}/cqube/dashboard/client_side"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    recurse: yes

- name: Starting / restarting the http-server
  become: yes
  shell: pm2 start client_side

- name: stop pm2 if running
  become: yes
  shell: pm2 stop server_side

- name: Delete .env
  file:
    path: "{{ base_dir }}/cqube/dashboard/server_side/.env"
    state: absent

- name: Updating .env
  template:
    src: angular.env.j2
    dest: "{{ base_dir }}/cqube/dashboard/server_side/.env"

- name: Starting NodeJS application
  become: yes
  shell: pm2 start server_side
