- name: create a virtual environment directory
  file:
    path: /opt/emission_server/flaskenv
    state: directory

- name: Copy requirements.txt
  copy:
    src: requirements.txt
    dest: /opt/emission_server/requirements.txt

- name: Manually create the initial virtualenv
  command:
    cmd: virtualenv /opt/emission_server/flaskenv -p python3
    creates: "/opt/emission_server/flaskenv"

- name: Install requirements
  become: yes
  pip:
    requirements: /opt/emission_server/requirements.txt
    virtualenv: /opt/emission_server/flaskenv
    virtualenv_python: /usr/bin/python3

- name: Creating environmental variables
  file:
    path: ../../development/python/env.py
    state: touch
    mode: u+rw,g+rw,o+rw

- name: Loading required data inside env.py file
  blockinfile:
        path: ../../development/python/env.py
        block: |
               DATABASE_URI = "postgresql://postgres:{{ db_passwd }}@localhost:5432/{{ emission_db_name }}"
               AWS_SECRET_KEY = "{{ s3_secret_key }}"
               AWS_ACCESS_KEY = "{{ s3_access_key }}"
               BUCKET_NAME = "{{ s3_emission_bucket }}"
               AWS_DEFAULT_REGION = "{{ aws_default_region }}"

- name: starting flask app
  shell: /opt/emission_server/flaskenv/bin/python server.py &
  args:
    chdir: ../../development/python

