- include_tasks: nifi_composite.yml
  tags: [ install, update ]

- include_tasks: nifi_crc_comp.yml
  tags: [ install, update ]
  when: nifi_crc

- include_tasks: nifi_attendance_comp.yml
  tags: [ install, update ]
  when: nifi_attendance

- include_tasks: nifi_semester_comp.yml
  tags: [ install, update ]
  when: nifi_semester

- include_tasks: nifi_infra_comp.yml
  tags: [ install, update ]
  when: nifi_infra

- include_tasks: nifi_diksha_comp.yml
  tags: [ install, update ]
  when: nifi_diksha

- include_tasks: nifi_udise_comp.yml
  tags: [ install, update ]
  when: nifi_udise

- include_tasks: nifi_pat_comp.yml
  tags: [ install, update ]
  when: nifi_pat
