- name: Fetch nifi root processor group id
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/process-groups/root
    method: GET
  register: processor_id

#--- Fetching the input port id of crc processor
- name: get port id of composite processor
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/flow/process-groups/{{ crc_pg_id[0].item.component.id }}
    method: GET
  loop: "{{ crc_pg_id[0].json | json_query('processGroupFlow.flow.outputPorts[*]') }}"
  when: item.component.name == 'crc_comp_output'
  register: port_list
  no_log: True

- set_fact:
    crc_port: "{{ port_list | json_query('results[?item.component.name == `crc_comp_output`]') }}"

#--- connection of crc output port to the composite input port 
- name: connecting crc output port and composite input port
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/process-groups/{{ processor_id.json.id }}/connections
    method: POST
    body_format: json
    status_code: 201
    body: {
  "revision": {
    "version": 0
  },
  "disconnectedNodeAcknowledged": false,
  "component": {
    "name": "",
    "source": {
      "id": "{{ crc_port[0].item.component.id }}",
      "groupId": "{{ crc_pg_id[0].item.component.id }}",
      "type": "OUTPUT_PORT"
    },
    "destination": {
      "id": "{{ composite_port[0].item.component.id }}",
      "groupId": "{{ composite_pg_id[0].item.component.id }}",
      "type": "INPUT_PORT"
    }
  }
}

- name: Enable crc output port
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/output-ports/{{ crc_port[0].item.component.id }}/run-status
    method: PUT
    body_format: json
    body: {"revision":{"version":"{{ crc_port[0].item.revision.version }}"},"state":"STOPPED","disconnectedNodeAcknowledged":false}
