- name: Fetch nifi root processor group id
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/process-groups/root
    method: GET
  register: processor_id

#--- Fetching output port of semester processor ---
- name: get port id of student assessment processor
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/flow/process-groups/{{ semester_pg_id[0].item.component.id }}
    method: GET
  loop: "{{ semester_pg_id[0].json | json_query('processGroupFlow.flow.outputPorts[*]') }}"
  when: item.component.name == 'student_assessment_comp_output'
  register: port_list
  no_log: True

- set_fact:
    semester_port: "{{ port_list | json_query('results[?item.component.name == `student_assessment_comp_output`]') }}"

#--- Connection of semester output port to the composite input port ---    
- name: connecting semester output port and composite input port
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/process-groups/{{ processor_id.json.id }}/connections
    method: POST
    body_format: json
    status_code: 201
    body: {
  "revision": {
    "version": 0
  },
  "disconnectedNodeAcknowledged": false,
  "component": {
    "name": "",
    "source": {
      "id": "{{ semester_port[0].item.component.id }}",
      "groupId": "{{ semester_pg_id[0].item.component.id }}",
      "type": "OUTPUT_PORT"
    },
    "destination": {
      "id": "{{ composite_port[0].item.component.id }}",
      "groupId": "{{ composite_pg_id[0].item.component.id }}",
      "type": "INPUT_PORT"
    }
  }
}

- name: Enable semester output port
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/output-ports/{{ semester_port[0].item.component.id }}/run-status
    method: PUT
    body_format: json
    body: {"revision":{"version":"{{ semester_port[0].item.revision.version }}"},"state":"STOPPED","disconnectedNodeAcknowledged":false}

