---
- name: Downloading keycloak
  get_url: 
    url: "{{ keycloak_url }}"
    dest: /tmp
  tags: install

- name: Removing existing keycloak files, if any
  file:
    path: "{{ keycloak_dir }}/keycloak"
    state: absent
  tags: install

- name: unpacking keycloak
  unarchive: 
    src: "/tmp/{{keycloak_archive}}"
    dest: "{{ keycloak_dir }}"
  tags: install

- name: Rename the extracted folder
  shell: mv {{ keycloak_dir }}/keycloak* {{ keycloak_dir }}/keycloak
  tags: install

- name: keycloak systemd setup
  template:
    owner: root
    group: root
    mode: 0644
    src: keycloak.service.j2
    dest: /etc/systemd/system/keycloak.service
  tags: install

- name: reload systemd
  shell: sudo systemctl daemon-reload
  tags: install

- name: keycloak systemd service enable and start
  service: 
    name: keycloak
    enabled: yes
    state: started
  tags: install

- name: creating postgresql conf in keycloak
  file:
    path: "{{ base_dir }}/cqube/keycloak/modules/system/layers/keycloak/org/postgresql/main"
    state: directory
  tags: install

- name: creating postgresql module.xml
  template:
    src: module.xml.j2
    dest: "{{ base_dir }}/cqube/keycloak/modules/system/layers/keycloak/org/postgresql/main/module.xml"
  tags: install

- name: Download Jar file
  get_url:
    url: https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.10/postgresql-42.2.10.jar
    dest: "{{ base_dir }}/cqube/keycloak/modules/system/layers/keycloak/org/postgresql/main/"
  tags: install

- name: changing configuration in standalone xml
  template:
    src: standalone.xml.j2
    dest: "{{ base_dir }}/cqube/keycloak/standalone/configuration/standalone.xml"
  tags: install

- name: keycloak systemd service enable and start
  service:
    name: keycloak
    state: restarted
  tags: install

- name: Waiting for keycloak to started.. 10 seconds
  pause:
    seconds: 10
  tags: install
 
- name: add-user-keycloak
  shell: ./add-user-keycloak.sh -u {{ keycloak_adm_user }} -p {{ keycloak_adm_passwd }}
  args:
    chdir: "{{ base_dir }}/cqube/keycloak/bin/"
  tags: install
